name: CD
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4.1.7

       - name: Setup Node.js environment
         uses: actions/setup-node@v4.0.2
         with:
           node-version: lts/Hydrogen
       - name: Cache
         uses: actions/cache@v4.0.2
         id: cache
         with:
           path: node_modules
           key: npm-packages-${{ hashFiles('../package-lock.json') }}

       - name: Install Dependencies
         if: steps.cache.outputs.cache-hit != 'true'
         run: npm install

       - name: Build
         run: npm run build


       - name: Docker Login
         uses: docker/login-action@v3.2.0
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
           
       - name: Docker Setup Buildx
         uses: docker/setup-buildx-action@v3.3.0

       - name: Build and push Docker images
         uses: docker/build-push-action@v6.1.0
         with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/namanmoo

       - name: SSH Remote Commands
         uses: appleboy/ssh-action@v1.0.3
         with:
           key: ${{ secrets.SSH_KEY }}
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           script: |
             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/namanmoo
             docker stop namanmoo
             docker run -d --rm --name namanmoo -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/namanmoo
